### ISSUE TITLE
Revisit constructing RawMultihash and Cid

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/tiny-multihash#13]

**Comment by vmx** [comment]
I'm currently looking into `rust-cid`. Could you please elaborate what this issue is about?

**Comment by dvc94ch** [comment]
Creating a cid looks like this:
Cid::new(Multihash::new().unwrap().to_raw().unwrap())
There should be a way to construct a cid without two unwraps.
Cid::new(Code::Sha2::digest()) should work. We possibly don't need the Multihash enum at all and can just use the derived code enum and RawMultihash

**Comment by vmx** [comment]
I see. That was exactly what I was hitting and I also think the current way is too ugly.

The problem is that `RawMultihash` could fail if the digest is bigger than the maximum size RawMultihash can hold.

What would be great would be if the `Multihash` derive could analyze the `Multihash` enum and figure out what the maximum size of the used digests are. Then it could generate a non-errorable `to_raw()` if it is possible (or probably better, less magic, error the compilation and you'd need to set a flag to no create the non-errorable `to_raw()`. But I don't think that's really possible.

Another way would be that we only implement a `try_to_raw()` automatically and people would need to implement a non-errorable `to_raw()` themselves. As an implementer you'd have the knowledge, whether you have larger digests or not.

**Comment by dvc94ch** [comment]
it's easy, just define a trait MultihashCode { digest()-> RawMultihash } and loose the Multihash enum

**Comment by vmx** [comment]
And we would implement such a `MultihashCode` trait for `Mutlihash` (and/or `Code`), but it won't be derived automatically?

**Comment by dvc94ch** [comment]
We already only support hashes <= 512 so I don't see the problem.

**Comment by vmx** [comment]
> We already only support hashes <= 512 so I don't see the problem.

By default. But users could specify bigger ones (e.g. they want a 1024 bit BLAKE3 hash). Making it panic in such cases seems to be too harsh, it should really be an error (runtime or compile time).

**Comment by dvc94ch** [comment]
We can define a marker trait for all sizes up to U64 and require it as a trait bound

**Comment by vmx** [comment]
That sounds cool. Could we even do that with the current code and make `to_raw()` non-errorable? My knowledge in regards to marker traits is limited.

**Comment by dvc94ch** [comment]
A marker trait is just an empty trait (pub trait My marker {})
